#!/usr/bin/env python
# -*- coding:utf-8 -*-
import rospy
import socket
from contextlib import closing

from ublox_msgs.msg import NavRELPOSNED

class SocketClass:
  def __init__(self):
    rospy.on_shutdown(self.shutdown)

    host = rospy.get_param('~ip_address', "192.168.12.100")
    port = rospy.get_param('~port', 54300)
    size = 1024
    
    self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    nav_pos = NavRELPOSNED()
    gps_pub = rospy.Publisher('ublox_gps/navrelposned', NavRELPOSNED, queue_size=10)

    try:
      self.sock.connect((host, port))
    except: return

    rate = rospy.Rate(100)
    while not rospy.is_shutdown():
      rate.sleep()  
      try:
        response = self.sock.recv(size)
        print response

        nav_pos.relPosN = 0
        nav_pos.relPosE = 0
        nav_pos.relPosD = 0
        nav_pos.flags   = 0
        gps_pub.publish(nav_pos)
      except: continue
    self.sock.close()

  def shutdown(self):
    try:
      self.sock.close()
    except: pass

if __name__ == '__main__':
  rospy.init_node('chairbot_rtklib', anonymous=True)
  try:
    SocketClass()
    rospy.loginfo("chairbot_rtklib node finished.")
  except rospy.ROSInterruptException:
    rospy.loginfo("chairbot_rtklib node finished.")