uint32[] id
---
uint64[] rostime
uint32[] id
float32[] x
float32[] y
float32[] z
float32[] theta
float32[] joint_waist_low
float32[] joint_waist_high
float32[] joint_arm_right_1
float32[] joint_arm_right_2
float32[] joint_arm_right_3
float32[] joint_arm_right_4
float32[] joint_arm_right_5
float32[] joint_arm_right_6
float32[] joint_arm_right_7
float32[] joint_arm_right_g
float32[] joint_arm_left_1
float32[] joint_arm_left_2
float32[] joint_arm_left_3
float32[] joint_arm_left_4
float32[] joint_arm_left_5
float32[] joint_arm_left_6
float32[] joint_arm_left_7
float32[] joint_arm_left_g
uint32[] state
uint32[] place
