uint64[] rostime
uint32[] id
float32[] x
float32[] y
float32[] z
float32[] weight
uint32[] state
uint32[] place
---
uint64[] rostime
uint32[] id
float32[] x
float32[] y
float32[] z
float32[] rr
float32[] rp
float32[] ry
float32[] weight
uint32[] state
uint32[] place
