uint8 robot_id
uint8 wagon_id
tms_msg_rp/rps_position robot_pos
tms_msg_rp/rps_joint_angle pre_robot_joint_angle
tms_msg_rp/rps_position wagon_pos
---
uint32 success
string message
uint8 grasp_wagon_type
float32 palm_th
tms_msg_rp/rps_joint_angle[] robot_joint_angle
tms_msg_rp/rps_position rel_control_point_pos
