#!/bin/sh
sudo apt-get install \
build-essential \
cmake-curses-gui \
libboost-all-dev \
libeigen3-dev \
libeigen3-doc \
libqt4-dev \
libqt4-opengl-dev \
qt4-dev-tools \
qt4-qtconfig \
qt4-doc-html \
libglew1.6-dev \
libopenscenegraph-dev \
openscenegraph-doc \
libyaml-dev \
gettext \
zlib1g-dev \
libjpeg8-dev \
libpng12-dev \
libode-dev \
libomniorb4-dev \
libcos4-dev \
omniidl \
omniorb-nameserver \
libgstreamer0.10-dev \
libgstreamer-plugins-base0.10-dev \
libsndfile1-dev \
libpulse-dev \
uuid-dev \
qhull-bin \
libqhull-dev \
liblapack-dev \
libqwt-dev \
ros-indigo-kobuki-msgs \
freeglut3-dev \
