// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "Mobility.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



YeRTUnitMobility::mobility_ptr YeRTUnitMobility::mobility_Helper::_nil() {
  return ::YeRTUnitMobility::mobility::_nil();
}

::CORBA::Boolean YeRTUnitMobility::mobility_Helper::is_nil(::YeRTUnitMobility::mobility_ptr p) {
  return ::CORBA::is_nil(p);

}

void YeRTUnitMobility::mobility_Helper::release(::YeRTUnitMobility::mobility_ptr p) {
  ::CORBA::release(p);
}

void YeRTUnitMobility::mobility_Helper::marshalObjRef(::YeRTUnitMobility::mobility_ptr obj, cdrStream& s) {
  ::YeRTUnitMobility::mobility::_marshalObjRef(obj, s);
}

YeRTUnitMobility::mobility_ptr YeRTUnitMobility::mobility_Helper::unmarshalObjRef(cdrStream& s) {
  return ::YeRTUnitMobility::mobility::_unmarshalObjRef(s);
}

void YeRTUnitMobility::mobility_Helper::duplicate(::YeRTUnitMobility::mobility_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

YeRTUnitMobility::mobility_ptr
YeRTUnitMobility::mobility::_duplicate(::YeRTUnitMobility::mobility_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

YeRTUnitMobility::mobility_ptr
YeRTUnitMobility::mobility::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


YeRTUnitMobility::mobility_ptr
YeRTUnitMobility::mobility::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

YeRTUnitMobility::mobility_ptr
YeRTUnitMobility::mobility::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_mobility _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_mobility* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_mobility;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* YeRTUnitMobility::mobility::_PD_repoId = "IDL:YeRTUnitMobility/mobility:1.0";


YeRTUnitMobility::_objref_mobility::~_objref_mobility() {
  
}


YeRTUnitMobility::_objref_mobility::_objref_mobility(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::YeRTUnitMobility::mobility::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
YeRTUnitMobility::_objref_mobility::_ptrToObjRef(const char* id)
{
  if( id == ::YeRTUnitMobility::mobility::_PD_repoId )
    return (::YeRTUnitMobility::mobility_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::YeRTUnitMobility::mobility::_PD_repoId) )
    return (::YeRTUnitMobility::mobility_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cboolean
class _0RL_cd_2dda428a655610cb_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_2dda428a655610cb_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Boolean result;
};

void _0RL_cd_2dda428a655610cb_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_2dda428a655610cb_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_2dda428a655610cb_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_00000000* tcd = (_0RL_cd_2dda428a655610cb_00000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->stop();


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::stop()
{
  _0RL_cd_2dda428a655610cb_00000000 _call_desc(_0RL_lcfn_2dda428a655610cb_10000000, "stop", 5);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_20000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_00000000* tcd = (_0RL_cd_2dda428a655610cb_00000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->clearAlarm();


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::clearAlarm()
{
  _0RL_cd_2dda428a655610cb_00000000 _call_desc(_0RL_lcfn_2dda428a655610cb_20000000, "clearAlarm", 11);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cboolean
class _0RL_cd_2dda428a655610cb_30000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_2dda428a655610cb_30000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Boolean arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_2dda428a655610cb_30000000::marshalArguments(cdrStream& _n)
{
  _n.marshalBoolean(arg_0);

}

void _0RL_cd_2dda428a655610cb_30000000::unmarshalArguments(cdrStream& _n)
{
  arg_0 = _n.unmarshalBoolean();

}

void _0RL_cd_2dda428a655610cb_30000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_2dda428a655610cb_30000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_2dda428a655610cb_30000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_40000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_30000000* tcd = (_0RL_cd_2dda428a655610cb_30000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->setPower(tcd->arg_0);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::setPower(::CORBA::Boolean OnOff)
{
  _0RL_cd_2dda428a655610cb_30000000 _call_desc(_0RL_lcfn_2dda428a655610cb_40000000, "setPower", 9);
  _call_desc.arg_0 = OnOff;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_30000000* tcd = (_0RL_cd_2dda428a655610cb_30000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->setServo(tcd->arg_0);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::setServo(::CORBA::Boolean OnOff)
{
  _0RL_cd_2dda428a655610cb_30000000 _call_desc(_0RL_lcfn_2dda428a655610cb_50000000, "setServo", 9);
  _call_desc.arg_0 = OnOff;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_o_cstring
class _0RL_cd_2dda428a655610cb_60000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_2dda428a655610cb_60000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_2dda428a655610cb_60000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);
  _n.marshalString(arg_0,0);

}

void _0RL_cd_2dda428a655610cb_60000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();
  arg_0 = _n.unmarshalString(0);

}

const char* const _0RL_cd_2dda428a655610cb_60000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_60000000* tcd = (_0RL_cd_2dda428a655610cb_60000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->getVersion(tcd->arg_0.out());


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::getVersion(::CORBA::String_out ver)
{
  _0RL_cd_2dda428a655610cb_60000000 _call_desc(_0RL_lcfn_2dda428a655610cb_70000000, "getVersion", 11);


  _invoke(_call_desc);
  ver = _call_desc.arg_0._retn();
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_80000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_00000000* tcd = (_0RL_cd_2dda428a655610cb_00000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->pause();


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::pause()
{
  _0RL_cd_2dda428a655610cb_00000000 _call_desc(_0RL_lcfn_2dda428a655610cb_80000000, "pause", 6);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_90000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_00000000* tcd = (_0RL_cd_2dda428a655610cb_00000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->resume();


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::resume()
{
  _0RL_cd_2dda428a655610cb_00000000 _call_desc(_0RL_lcfn_2dda428a655610cb_90000000, "resume", 7);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_a0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_00000000* tcd = (_0RL_cd_2dda428a655610cb_00000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->unlock();


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::unlock()
{
  _0RL_cd_2dda428a655610cb_00000000 _call_desc(_0RL_lcfn_2dda428a655610cb_a0000000, "unlock", 7);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cunsigned_plong_o_cboolean
class _0RL_cd_2dda428a655610cb_b0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_2dda428a655610cb_b0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::ULong arg_0;
  ::CORBA::Boolean arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_2dda428a655610cb_b0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_2dda428a655610cb_b0000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::ULong&)arg_0 <<= _n;

}

void _0RL_cd_2dda428a655610cb_b0000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);
  _n.marshalBoolean(arg_1);

}

void _0RL_cd_2dda428a655610cb_b0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();
  arg_1 = _n.unmarshalBoolean();

}

const char* const _0RL_cd_2dda428a655610cb_b0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_c0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_b0000000* tcd = (_0RL_cd_2dda428a655610cb_b0000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->getServoStatus(tcd->arg_0, tcd->arg_1);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::getServoStatus(::CORBA::ULong axisid, ::CORBA::Boolean& status)
{
  _0RL_cd_2dda428a655610cb_b0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_c0000000, "getServoStatus", 15);
  _call_desc.arg_0 = axisid;

  _invoke(_call_desc);
  status = _call_desc.arg_1;
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cshort_o_cshort_o_cAlarmSeq
class _0RL_cd_2dda428a655610cb_d0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_2dda428a655610cb_d0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Short arg_0;
  ::CORBA::Short arg_1;
  AlarmSeq_var arg_2;
  ::CORBA::Boolean result;
};

void _0RL_cd_2dda428a655610cb_d0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_2dda428a655610cb_d0000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Short&)arg_0 <<= _n;

}

void _0RL_cd_2dda428a655610cb_d0000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);
  arg_1 >>= _n;
  (const AlarmSeq&) arg_2 >>= _n;

}

void _0RL_cd_2dda428a655610cb_d0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();
  (::CORBA::Short&)arg_1 <<= _n;
  arg_2 = new AlarmSeq;
  (AlarmSeq&)arg_2 <<= _n;

}

const char* const _0RL_cd_2dda428a655610cb_d0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_e0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_d0000000* tcd = (_0RL_cd_2dda428a655610cb_d0000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->getActiveAlarm(tcd->arg_0, tcd->arg_1, tcd->arg_2.out());


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::getActiveAlarm(::CORBA::Short numOfAlarm, ::CORBA::Short& numOfActiveAlarm, ::AlarmSeq_out activeAlarms)
{
  _0RL_cd_2dda428a655610cb_d0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_e0000000, "getActiveAlarm", 15);
  _call_desc.arg_0 = numOfAlarm;

  _invoke(_call_desc);
  numOfActiveAlarm = _call_desc.arg_1;
  activeAlarms = _call_desc.arg_2._retn();
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cdouble_i_cdouble_i_cdouble
class _0RL_cd_2dda428a655610cb_f0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_2dda428a655610cb_f0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  ::CORBA::Double arg_1;
  ::CORBA::Double arg_2;
  ::CORBA::Boolean result;
};

void _0RL_cd_2dda428a655610cb_f0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;

}

void _0RL_cd_2dda428a655610cb_f0000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;
  (::CORBA::Double&)arg_1 <<= _n;
  (::CORBA::Double&)arg_2 <<= _n;

}

void _0RL_cd_2dda428a655610cb_f0000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_2dda428a655610cb_f0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_2dda428a655610cb_f0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_01000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_f0000000* tcd = (_0RL_cd_2dda428a655610cb_f0000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->setPosition(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::setPosition(::CORBA::Double x_, ::CORBA::Double y_, ::CORBA::Double theta_)
{
  _0RL_cd_2dda428a655610cb_f0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_01000000, "setPosition", 12);
  _call_desc.arg_0 = x_;
  _call_desc.arg_1 = y_;
  _call_desc.arg_2 = theta_;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_o_cdouble_o_cdouble_o_cdouble
class _0RL_cd_2dda428a655610cb_11000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_2dda428a655610cb_11000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  ::CORBA::Double arg_1;
  ::CORBA::Double arg_2;
  ::CORBA::Boolean result;
};

void _0RL_cd_2dda428a655610cb_11000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;

}

void _0RL_cd_2dda428a655610cb_11000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();
  (::CORBA::Double&)arg_0 <<= _n;
  (::CORBA::Double&)arg_1 <<= _n;
  (::CORBA::Double&)arg_2 <<= _n;

}

const char* const _0RL_cd_2dda428a655610cb_11000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_21000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_11000000* tcd = (_0RL_cd_2dda428a655610cb_11000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->getPosition(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::getPosition(::CORBA::Double& x_, ::CORBA::Double& y_, ::CORBA::Double& theta_)
{
  _0RL_cd_2dda428a655610cb_11000000 _call_desc(_0RL_lcfn_2dda428a655610cb_21000000, "getPosition", 12);


  _invoke(_call_desc);
  x_ = _call_desc.arg_0;
  y_ = _call_desc.arg_1;
  theta_ = _call_desc.arg_2;
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_o_cshort_o_cstring
class _0RL_cd_2dda428a655610cb_31000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_2dda428a655610cb_31000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Short arg_0;
  ::CORBA::String_var arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_2dda428a655610cb_31000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);
  arg_0 >>= _n;
  _n.marshalString(arg_1,0);

}

void _0RL_cd_2dda428a655610cb_31000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();
  (::CORBA::Short&)arg_0 <<= _n;
  arg_1 = _n.unmarshalString(0);

}

const char* const _0RL_cd_2dda428a655610cb_31000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_41000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_31000000* tcd = (_0RL_cd_2dda428a655610cb_31000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->getState(tcd->arg_0, tcd->arg_1.out());


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::getState(::CORBA::Short& state, ::CORBA::String_out msg)
{
  _0RL_cd_2dda428a655610cb_31000000 _call_desc(_0RL_lcfn_2dda428a655610cb_41000000, "getState", 9);


  _invoke(_call_desc);
  state = _call_desc.arg_0;
  msg = _call_desc.arg_1._retn();
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cdouble_i_cdouble
class _0RL_cd_2dda428a655610cb_51000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_2dda428a655610cb_51000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  ::CORBA::Double arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_2dda428a655610cb_51000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_2dda428a655610cb_51000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;
  (::CORBA::Double&)arg_1 <<= _n;

}

void _0RL_cd_2dda428a655610cb_51000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_2dda428a655610cb_51000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_2dda428a655610cb_51000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_61000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_51000000* tcd = (_0RL_cd_2dda428a655610cb_51000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->setVelocity(tcd->arg_0, tcd->arg_1);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::setVelocity(::CORBA::Double velT, ::CORBA::Double velR)
{
  _0RL_cd_2dda428a655610cb_51000000 _call_desc(_0RL_lcfn_2dda428a655610cb_61000000, "setVelocity", 12);
  _call_desc.arg_0 = velT;
  _call_desc.arg_1 = velR;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_71000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_51000000* tcd = (_0RL_cd_2dda428a655610cb_51000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->setAcceleration(tcd->arg_0, tcd->arg_1);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::setAcceleration(::CORBA::Double accT, ::CORBA::Double accR)
{
  _0RL_cd_2dda428a655610cb_51000000 _call_desc(_0RL_lcfn_2dda428a655610cb_71000000, "setAcceleration", 16);
  _call_desc.arg_0 = accT;
  _call_desc.arg_1 = accR;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cshort
class _0RL_cd_2dda428a655610cb_81000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_2dda428a655610cb_81000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Short arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_2dda428a655610cb_81000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_2dda428a655610cb_81000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Short&)arg_0 <<= _n;

}

void _0RL_cd_2dda428a655610cb_81000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_2dda428a655610cb_81000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_2dda428a655610cb_81000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_91000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_81000000* tcd = (_0RL_cd_2dda428a655610cb_81000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->setJogTimeout(tcd->arg_0);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::setJogTimeout(::CORBA::Short timeout)
{
  _0RL_cd_2dda428a655610cb_81000000 _call_desc(_0RL_lcfn_2dda428a655610cb_91000000, "setJogTimeout", 14);
  _call_desc.arg_0 = timeout;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_a1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_f0000000* tcd = (_0RL_cd_2dda428a655610cb_f0000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->moveJog(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::moveJog(::CORBA::Double vx_, ::CORBA::Double vy_, ::CORBA::Double vtheta_)
{
  _0RL_cd_2dda428a655610cb_f0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_a1000000, "moveJog", 8);
  _call_desc.arg_0 = vx_;
  _call_desc.arg_1 = vy_;
  _call_desc.arg_2 = vtheta_;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cdouble
class _0RL_cd_2dda428a655610cb_b1000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_2dda428a655610cb_b1000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_2dda428a655610cb_b1000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_2dda428a655610cb_b1000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;

}

void _0RL_cd_2dda428a655610cb_b1000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_2dda428a655610cb_b1000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_2dda428a655610cb_b1000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_c1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_b1000000* tcd = (_0RL_cd_2dda428a655610cb_b1000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->moveForward(tcd->arg_0);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::moveForward(::CORBA::Double x_)
{
  _0RL_cd_2dda428a655610cb_b1000000 _call_desc(_0RL_lcfn_2dda428a655610cb_c1000000, "moveForward", 12);
  _call_desc.arg_0 = x_;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_d1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_b1000000* tcd = (_0RL_cd_2dda428a655610cb_b1000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->moveTurn(tcd->arg_0);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::moveTurn(::CORBA::Double theta_)
{
  _0RL_cd_2dda428a655610cb_b1000000 _call_desc(_0RL_lcfn_2dda428a655610cb_d1000000, "moveTurn", 9);
  _call_desc.arg_0 = theta_;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_e1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_b1000000* tcd = (_0RL_cd_2dda428a655610cb_b1000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->moveTurnContinuous(tcd->arg_0);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::moveTurnContinuous(::CORBA::Double theta_)
{
  _0RL_cd_2dda428a655610cb_b1000000 _call_desc(_0RL_lcfn_2dda428a655610cb_e1000000, "moveTurnContinuous", 19);
  _call_desc.arg_0 = theta_;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_f1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_f0000000* tcd = (_0RL_cd_2dda428a655610cb_f0000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->moveLinear(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::moveLinear(::CORBA::Double x_, ::CORBA::Double y_, ::CORBA::Double theta_)
{
  _0RL_cd_2dda428a655610cb_f0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_f1000000, "moveLinear", 11);
  _call_desc.arg_0 = x_;
  _call_desc.arg_1 = y_;
  _call_desc.arg_2 = theta_;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_02000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_f0000000* tcd = (_0RL_cd_2dda428a655610cb_f0000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->moveLinearAbs(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::moveLinearAbs(::CORBA::Double x_, ::CORBA::Double y_, ::CORBA::Double theta_)
{
  _0RL_cd_2dda428a655610cb_f0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_02000000, "moveLinearAbs", 14);
  _call_desc.arg_0 = x_;
  _call_desc.arg_1 = y_;
  _call_desc.arg_2 = theta_;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_12000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_f0000000* tcd = (_0RL_cd_2dda428a655610cb_f0000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->moveCircular(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::moveCircular(::CORBA::Double centerX_, ::CORBA::Double centerY_, ::CORBA::Double angle)
{
  _0RL_cd_2dda428a655610cb_f0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_12000000, "moveCircular", 13);
  _call_desc.arg_0 = centerX_;
  _call_desc.arg_1 = centerY_;
  _call_desc.arg_2 = angle;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_22000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_f0000000* tcd = (_0RL_cd_2dda428a655610cb_f0000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->moveContinuous(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::moveContinuous(::CORBA::Double x_, ::CORBA::Double y_, ::CORBA::Double theta_)
{
  _0RL_cd_2dda428a655610cb_f0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_22000000, "moveContinuous", 15);
  _call_desc.arg_0 = x_;
  _call_desc.arg_1 = y_;
  _call_desc.arg_2 = theta_;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_32000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_51000000* tcd = (_0RL_cd_2dda428a655610cb_51000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->moveWagon(tcd->arg_0, tcd->arg_1);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::moveWagon(::CORBA::Double x_, ::CORBA::Double y_)
{
  _0RL_cd_2dda428a655610cb_51000000 _call_desc(_0RL_lcfn_2dda428a655610cb_32000000, "moveWagon", 10);
  _call_desc.arg_0 = x_;
  _call_desc.arg_1 = y_;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_42000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_51000000* tcd = (_0RL_cd_2dda428a655610cb_51000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->moveWagonAbs(tcd->arg_0, tcd->arg_1);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::moveWagonAbs(::CORBA::Double x_, ::CORBA::Double y_)
{
  _0RL_cd_2dda428a655610cb_51000000 _call_desc(_0RL_lcfn_2dda428a655610cb_42000000, "moveWagonAbs", 13);
  _call_desc.arg_0 = x_;
  _call_desc.arg_1 = y_;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_o_cshort
class _0RL_cd_2dda428a655610cb_52000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_2dda428a655610cb_52000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Short arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_2dda428a655610cb_52000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);
  arg_0 >>= _n;

}

void _0RL_cd_2dda428a655610cb_52000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();
  (::CORBA::Short&)arg_0 <<= _n;

}

const char* const _0RL_cd_2dda428a655610cb_52000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_2dda428a655610cb_62000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_2dda428a655610cb_52000000* tcd = (_0RL_cd_2dda428a655610cb_52000000*)cd;
  YeRTUnitMobility::_impl_mobility* impl = (YeRTUnitMobility::_impl_mobility*) svnt->_ptrToInterface(YeRTUnitMobility::mobility::_PD_repoId);
  tcd->result = impl->getBatteryVoltage(tcd->arg_0);


}

::CORBA::Boolean YeRTUnitMobility::_objref_mobility::getBatteryVoltage(::CORBA::Short& voltage)
{
  _0RL_cd_2dda428a655610cb_52000000 _call_desc(_0RL_lcfn_2dda428a655610cb_62000000, "getBatteryVoltage", 18);


  _invoke(_call_desc);
  voltage = _call_desc.arg_0;
  return _call_desc.result;


}
YeRTUnitMobility::_pof_mobility::~_pof_mobility() {}


omniObjRef*
YeRTUnitMobility::_pof_mobility::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::YeRTUnitMobility::_objref_mobility(ior, id);
}


::CORBA::Boolean
YeRTUnitMobility::_pof_mobility::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::YeRTUnitMobility::mobility::_PD_repoId) )
    return 1;
  
  return 0;
}

const YeRTUnitMobility::_pof_mobility _the_pof_YeRTUnitMobility_mmobility;

YeRTUnitMobility::_impl_mobility::~_impl_mobility() {}


::CORBA::Boolean
YeRTUnitMobility::_impl_mobility::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "stop") ) {

    _0RL_cd_2dda428a655610cb_00000000 _call_desc(_0RL_lcfn_2dda428a655610cb_10000000, "stop", 5, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "clearAlarm") ) {

    _0RL_cd_2dda428a655610cb_00000000 _call_desc(_0RL_lcfn_2dda428a655610cb_20000000, "clearAlarm", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setPower") ) {

    _0RL_cd_2dda428a655610cb_30000000 _call_desc(_0RL_lcfn_2dda428a655610cb_40000000, "setPower", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setServo") ) {

    _0RL_cd_2dda428a655610cb_30000000 _call_desc(_0RL_lcfn_2dda428a655610cb_50000000, "setServo", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getVersion") ) {

    _0RL_cd_2dda428a655610cb_60000000 _call_desc(_0RL_lcfn_2dda428a655610cb_70000000, "getVersion", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "pause") ) {

    _0RL_cd_2dda428a655610cb_00000000 _call_desc(_0RL_lcfn_2dda428a655610cb_80000000, "pause", 6, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "resume") ) {

    _0RL_cd_2dda428a655610cb_00000000 _call_desc(_0RL_lcfn_2dda428a655610cb_90000000, "resume", 7, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "unlock") ) {

    _0RL_cd_2dda428a655610cb_00000000 _call_desc(_0RL_lcfn_2dda428a655610cb_a0000000, "unlock", 7, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getServoStatus") ) {

    _0RL_cd_2dda428a655610cb_b0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_c0000000, "getServoStatus", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getActiveAlarm") ) {

    _0RL_cd_2dda428a655610cb_d0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_e0000000, "getActiveAlarm", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setPosition") ) {

    _0RL_cd_2dda428a655610cb_f0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_01000000, "setPosition", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getPosition") ) {

    _0RL_cd_2dda428a655610cb_11000000 _call_desc(_0RL_lcfn_2dda428a655610cb_21000000, "getPosition", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getState") ) {

    _0RL_cd_2dda428a655610cb_31000000 _call_desc(_0RL_lcfn_2dda428a655610cb_41000000, "getState", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setVelocity") ) {

    _0RL_cd_2dda428a655610cb_51000000 _call_desc(_0RL_lcfn_2dda428a655610cb_61000000, "setVelocity", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setAcceleration") ) {

    _0RL_cd_2dda428a655610cb_51000000 _call_desc(_0RL_lcfn_2dda428a655610cb_71000000, "setAcceleration", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setJogTimeout") ) {

    _0RL_cd_2dda428a655610cb_81000000 _call_desc(_0RL_lcfn_2dda428a655610cb_91000000, "setJogTimeout", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "moveJog") ) {

    _0RL_cd_2dda428a655610cb_f0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_a1000000, "moveJog", 8, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "moveForward") ) {

    _0RL_cd_2dda428a655610cb_b1000000 _call_desc(_0RL_lcfn_2dda428a655610cb_c1000000, "moveForward", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "moveTurn") ) {

    _0RL_cd_2dda428a655610cb_b1000000 _call_desc(_0RL_lcfn_2dda428a655610cb_d1000000, "moveTurn", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "moveTurnContinuous") ) {

    _0RL_cd_2dda428a655610cb_b1000000 _call_desc(_0RL_lcfn_2dda428a655610cb_e1000000, "moveTurnContinuous", 19, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "moveLinear") ) {

    _0RL_cd_2dda428a655610cb_f0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_f1000000, "moveLinear", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "moveLinearAbs") ) {

    _0RL_cd_2dda428a655610cb_f0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_02000000, "moveLinearAbs", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "moveCircular") ) {

    _0RL_cd_2dda428a655610cb_f0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_12000000, "moveCircular", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "moveContinuous") ) {

    _0RL_cd_2dda428a655610cb_f0000000 _call_desc(_0RL_lcfn_2dda428a655610cb_22000000, "moveContinuous", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "moveWagon") ) {

    _0RL_cd_2dda428a655610cb_51000000 _call_desc(_0RL_lcfn_2dda428a655610cb_32000000, "moveWagon", 10, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "moveWagonAbs") ) {

    _0RL_cd_2dda428a655610cb_51000000 _call_desc(_0RL_lcfn_2dda428a655610cb_42000000, "moveWagonAbs", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getBatteryVoltage") ) {

    _0RL_cd_2dda428a655610cb_52000000 _call_desc(_0RL_lcfn_2dda428a655610cb_62000000, "getBatteryVoltage", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
YeRTUnitMobility::_impl_mobility::_ptrToInterface(const char* id)
{
  if( id == ::YeRTUnitMobility::mobility::_PD_repoId )
    return (::YeRTUnitMobility::_impl_mobility*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::YeRTUnitMobility::mobility::_PD_repoId) )
    return (::YeRTUnitMobility::_impl_mobility*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
YeRTUnitMobility::_impl_mobility::_mostDerivedRepoId()
{
  return ::YeRTUnitMobility::mobility::_PD_repoId;
}

POA_YeRTUnitMobility::mobility::~mobility() {}

