ibs: CIntelCab Class Reference
CIntelCab Class Reference
Public Member Functions
CIntelCab (int stage_num=IC_STAGES_MAX)
~CIntelCab ()
void PrintObjInfo ()
int UpdateObj (int stageNo, CTagOBJ *cInOut)
Data Fields
CTR3 cTR3
CStage cStage [IC_STAGES_MAX]
int mStageNum
int fd
Private Member Functions
bool Setup (int stage_num)
bool Close ()
Detailed Description
Definition at line 190 of file ibs.cpp.
Constructor & Destructor Documentation
CIntelCab::CIntelCab (int stage_num = IC_STAGES_MAX) inline
Definition at line 196 of file ibs.cpp.
References Setup().
{
         Setup(stage_num); };
CIntelCab::~CIntelCab () inline
Definition at line 198 of file ibs.cpp.
                  {
         Close(); };
Member Function Documentation
bool CIntelCab::Close () private
Definition at line 718 of file ibs.cpp.
                       {
     return true; }
void CIntelCab::PrintObjInfo ()
Definition at line 722 of file ibs.cpp.
References cStage, CStage::cTagObj, CTagOBJ::mComment, CTagOBJ::mName, CStage::mName, CStage::mObjNum, mStageNum, CTagOBJ::mUID, CTagOBJ::mWeight, CTagOBJ::mX, and CTagOBJ::mY.
Referenced by main().
{
     CTagOBJ  *cObj;
     for (int i = 0; i < mStageNum; i++) {
         std::cout << "\n" << std::setw(20) << std::setfill(':') << cStage[i].mName << "::::::::::" << std::endl;
         for (int j = 0; j < cStage[i].mObjNum; j++) {
             cObj = &(cStage[i].cTagObj[j]);
             printf("%3d:  UID->", j + 1);
             std::cout << cObj->mUID;
             printf("  Weight=%4d  X=%4.0f Y=%4.0f", cObj->mWeight, cObj->mX, cObj->mY);
             std::cout << " <" << cObj->mName << ":" << cObj->mComment << ">" << std::endl; } } }
bool CIntelCab::Setup (int stage_num) private
Definition at line 713 of file ibs.cpp.
References mStageNum.
Referenced by CIntelCab().
{
     mStageNum = stage_num;
     return true; }
int CIntelCab::UpdateObj (int stageNo, CTagOBJ * cInOut)
Definition at line 735 of file ibs.cpp.
References CTR3::AntennaPowerOFF(), CTR3::AntennaPowerON(), CStage::cLoadCell, cStage, CStage::cTagObj, cTR3, CTR3::GetTagDiff(), CLoadCell::GetWeightDiff(), IC_OBJECT_IN, IC_OBJECT_MOVE, IC_OBJECT_OUT, IC_OBJECT_STAY, IC_STAGES_MAX, LC_MAX_SENSOR_NUM, CStage::mAntenna, CTagOBJ::mComment, CTagOBJ::mDiffs, CTagOBJ::mName, CStage::mObjNum, mStageNum, CTagOBJ::mUID, CTagOBJ::mWeight, CTagOBJ::mX, CTagOBJ::mY, CTR3::SetAntenna(), and TR3_TAG_MAX.
Referenced by main().
{
     static CTagOBJ  cObj, cObjIn[IC_STAGES_MAX], cObjOut[IC_STAGES_MAX];
     static int InOutTag[IC_STAGES_MAX], InOutLC[IC_STAGES_MAX];
     int value = IC_OBJECT_STAY;
     if (No >= mStageNum)
         return IC_OBJECT_STAY;
     //タグの増減チェック
     cTR3.AntennaPowerON();
     if (mStageNum == 1) {
         cTR3.SetAntenna(cStage[No].mAntenna + 1); }
     int inout = cTR3.GetTagDiff(cObj.mUID, cStage[No].mAntenna);
     cTR3.AntennaPowerOFF();
     //タグ検出
     if (inout > 0) {
         InOutTag[No] = 1;
         cObjIn[No] = cObj; }
     //出庫
     else if ( inout < 0 ) {
         for (int i = 0; i < cStage[No].mObjNum; i++) {
             if (cStage[No].cTagObj.at(i).mUID.compare(cObj.mUID) == 0) {
                 cStage[No].cTagObj.erase(cStage[No].cTagObj.begin() + i);
                 cStage[No].mObjNum = (int)cStage[No].cTagObj.size();
                 InOutLC[No] = 0;
                 break; } }
         InOutTag[No] = 0;
         *cInOut = cObj;
         value = IC_OBJECT_OUT; }
     //ロードセルの増減チェック
     cObj.mWeight = cStage[No].cLoadCell.GetWeightDiff(&cObj.mX, &cObj.mY, cObj.mDiffs);
     if ( (cObj.mWeight > 0) && (InOutTag[No] > 0) ) {
         //入庫
         cObj.mUID = cObjIn[No].mUID;
         cStage[No].cTagObj.push_back(cObj);
         cStage[No].mObjNum = (int)cStage[No].cTagObj.size();
         InOutTag[No] = 0;
         InOutLC[No]  = 0;
         *cInOut = cObj;
         value = IC_OBJECT_IN; }
     else if ( (cObj.mWeight > 0) && (InOutLC[No] < 0) ) {
         //庫内移動
         int cnt = TR3_TAG_MAX;
         for (int i = 0; i < cStage[No].mObjNum; i++) {
             if (cStage[No].cTagObj.at(i).mUID.compare(cObjOut[No].mUID) == 0) {
                 cnt = i;
                 break; } }
         if (cnt != TR3_TAG_MAX) {
             cStage[No].cTagObj.at(cnt) = cObj;
             cStage[No].cTagObj.at(cnt).mUID     = cObjOut[No].mUID;
             cStage[No].cTagObj.at(cnt).mName    = cObjOut[No].mName;
             cStage[No].cTagObj.at(cnt).mComment = cObjOut[No].mComment;
             InOutLC[No] = 0;
             *cInOut = cStage[No].cTagObj.at(cnt);
             value = IC_OBJECT_MOVE; } }
     //タグ無し物品の入庫
     else {}
     //持ち上げ
     if (cObj.mWeight < 0) {
         int comp = 5000;
         int cnt = TR3_TAG_MAX;
         for (int i = 0; i < cStage[No].mObjNum; i++) {
             int sum = 0;
             for (int j = 0; j < LC_MAX_SENSOR_NUM; j++) {
                 sum += abs(abs(cStage[No].cTagObj.at(i).mDiffs[j]) - abs(cObj.mDiffs[j])); }
             if (sum < comp) {
                 comp = sum;
                 cnt = i; } }
         if (cnt != TR3_TAG_MAX) {
             cObjOut[No] = cStage[No].cTagObj.at(cnt);
             InOutLC[No] = -1; } }
     return value; }
Field Documentation
CStage CIntelCab::cStage[IC_STAGES_MAX]
Definition at line 201 of file ibs.cpp.
Referenced by main(), PrintObjInfo(), and UpdateObj().
CTR3 CIntelCab::cTR3
Definition at line 199 of file ibs.cpp.
Referenced by main(), and UpdateObj().
int CIntelCab::fd
Definition at line 207 of file ibs.cpp.
int CIntelCab::mStageNum
Definition at line 202 of file ibs.cpp.
Referenced by main(), PrintObjInfo(), Setup(), and UpdateObj().
The documentation for this class was generated from the following file:
src/ibs.cpp