ibs: CTR3 Class Reference
CTR3 Class Reference
Public Member Functions
CTR3 ()
~CTR3 ()
bool Setup ()
int SetAntenna (unsigned char AN=TR3_ANT1)
bool AntennaPowerON ()
bool AntennaPowerOFF ()
void PrintTagUIDs ()
int GetTagDiff (std::string &diffUID, unsigned char AN)
Data Fields
int mTagNum [TR3_USED_ANT_NUM]
number of enxisting tags by the antenna
unsigned char mTagUIDs [TR3_USED_ANT_NUM][TR3_TAG_MAX][TR3_UID_SIZE]
same as mUIDs. should be replaced.
vec_str mUIDs [TR3_USED_ANT_NUM]
UIDs of existing tags.
int fd
Private Member Functions
bool Close ()
int AddChecksum ()
int Inventory2 ()
Private Attributes
struct termios oldtio newtio
unsigned char mCommand [TR3_MAX_COMMAND_SIZE]
int mActiveAntenna
true active antenna returned by serial
Detailed Description
Definition at line 122 of file ibs.cpp.
Constructor & Destructor Documentation
CTR3::CTR3 () inline
Definition at line 131 of file ibs.cpp.
 {};
CTR3::~CTR3 () inline
Definition at line 132 of file ibs.cpp.
             {
         Close(); };
Member Function Documentation
int CTR3::AddChecksum () private
Definition at line 656 of file ibs.cpp.
References mCommand, TR3_CR, and TR3_ETX.
Referenced by AntennaPowerOFF(), AntennaPowerON(), Inventory2(), and SetAntenna().
                       {
     int num = (int)mCommand[3] + 5;
     mCommand[num - 1] = TR3_ETX;
     mCommand[num + 1] = TR3_CR;
     mCommand[num] = 0x00;
     for (int i = 0; i < num; i++) {
         mCommand[num] += mCommand[i]; }
     return num + 2; }
bool CTR3::AntennaPowerOFF ()
Definition at line 492 of file ibs.cpp.
References AddChecksum(), fd, mCommand, newtio, PORT_TR, and TR3_ACK.
Referenced by main(), and CIntelCab::UpdateObj().
{
     // unsigned long num;
     unsigned char buf[100];
     mCommand[2] = 0x4E; //コマンド
     mCommand[3] = 0x02; //データ長
     mCommand[4] = 0x9E; //コマンド詳細
     mCommand[5] = 0x00; //パワーOFF
     memset(&buf, 0, sizeof(buf));
     //通信関連初期化
     if ( (fd = open(PORT_TR.c_str(), (O_RDWR | O_NOCTTY) )) < 0 ) {
         printf("FAILED:TR3->OpenComPort: PORT_TR \n");
         exit(-1); }
     tcgetattr(fd, &oldtio);         /* 現在のシリアルポートの設定を待避させる*/
     memset(&newtio, 0, sizeof(newtio));
     newtio.c_cflag = B38400 | CS8 | CLOCAL | CREAD;
     newtio.c_iflag = IGNPAR | ICRNL;
     newtio.c_oflag = 0;
     newtio.c_lflag = ICANON;
     tcflush(fd, TCIFLUSH);
     tcsetattr(fd, TCSANOW, &newtio);
     AddChecksum();
     write(fd, mCommand, sizeof(mCommand));
     read(fd, buf, 9);
     if ( buf[2] != TR3_ACK ) {
         read(fd, buf, 100);
         std::cerr << "TR3: SendCommandError -> AntennaPowerOFF" << std::endl;
         return false; }
     tcsetattr(fd, TCSANOW, &oldtio);  /* 退避させた設定に戻す */
     close(fd);
     return true; }
bool CTR3::AntennaPowerON ()
Definition at line 449 of file ibs.cpp.
References AddChecksum(), fd, mCommand, newtio, PORT_TR, and TR3_ACK.
Referenced by CIntelCab::UpdateObj().
{
     // unsigned long num;
     unsigned char buf[100];
     // unsigned char cmd[9] = {0x02, 0x00, 0x4e, 0x02, 0x9e, 0x01, 0x03, 0xf4, 0x0d};
     mCommand[2] = 0x4E; //コマンド
     mCommand[3] = 0x02; //データ長
     mCommand[4] = 0x9E; //コマンド詳細
     mCommand[5] = 0x01; //パワーON
     memset(&buf, 0, sizeof(buf));
     //通信関連初期化
     if ( (fd = open(PORT_TR.c_str(), (O_RDWR | O_NOCTTY) )) < 0 ) {
         printf("FAILED:TR3->OpenComPort: PORT_TR \n");
         exit(-1); }
     tcgetattr(fd, &oldtio);         /* 現在のシリアルポートの設定を待避させる*/
     memset(&newtio, 0, sizeof(newtio));
     newtio.c_cflag = B38400 | CS8 | CLOCAL | CREAD;
     newtio.c_iflag = IGNPAR | ICRNL;
     newtio.c_oflag = 0;
     newtio.c_lflag = ICANON;
     tcflush(fd, TCIFLUSH);
     tcsetattr(fd, TCSANOW, &newtio);
     AddChecksum();
     write(fd, mCommand, sizeof(mCommand));
     read(fd, buf, 9);
     if (buf[2] != TR3_ACK) {
         read(fd, buf, 100);
         std::cerr << "TR3: SendCommandError -> AntennaPowerON" << std::endl;
         return false; }
     tcsetattr(fd, TCSANOW, &oldtio);  /* 退避させた設定に戻す */
     close(fd);
     return true; }
bool CTR3::Close () private
Definition at line 402 of file ibs.cpp.
References fd.
                  {
     close(fd);
     std::cout << "CLOSED: TR3" << std::endl;
     return true; }
int CTR3::GetTagDiff (std::string & diffUID, unsigned char AN)
Todo:
insert "vec_str preUIDs" here and remove "mTagUIDs[][][]"
Definition at line 595 of file ibs.cpp.
References Inventory2(), mActiveAntenna, mTagNum, mTagUIDs, mUIDs, SetAntenna(), and vec_str.
Referenced by CIntelCab::UpdateObj().
{
     SetAntenna(AN);
     if (Inventory2() == -1) {
         return 0; }
     vec_str preUIDs = mUIDs[mActiveAntenna];
     mUIDs[mActiveAntenna].clear();
     for (int i = 0; i < mTagNum[mActiveAntenna]; i++) {
         char hex[17];
         sprintf(hex, "%02X%02X%02X%02X%02X%02X%02X%02X",
                 mTagUIDs[mActiveAntenna][i][0], mTagUIDs[mActiveAntenna][i][1], mTagUIDs[mActiveAntenna][i][2], mTagUIDs[mActiveAntenna][i][3],
                 mTagUIDs[mActiveAntenna][i][4], mTagUIDs[mActiveAntenna][i][5], mTagUIDs[mActiveAntenna][i][6], mTagUIDs[mActiveAntenna][i][7]);
         mUIDs[mActiveAntenna].push_back(std::string(hex)); }
     mTagNum[mActiveAntenna] = (int)mUIDs[mActiveAntenna].size();
     //タグの増減の確認
     std::sort(mUIDs[mActiveAntenna].begin(), mUIDs[mActiveAntenna].end());
     // IDにあってpreIDにない => 追加された物品ID
     vec_str increase;
     std::set_difference(mUIDs[mActiveAntenna].begin(), mUIDs[mActiveAntenna].end(), preUIDs.begin(), preUIDs.end(),
                         std::inserter(increase, increase.begin()));
     // preIDにあってIDにない => 取り除かれた物品ID
     vec_str decrease;
     std::set_difference(preUIDs.begin(), preUIDs.end(), mUIDs[mActiveAntenna].begin(), mUIDs[mActiveAntenna].end(),
                         std::inserter(decrease, decrease.begin()));
     // 増減なし
     if ( (increase.size() == 0) && (decrease.size() == 0) ) {
         return 0; }
     // 物品追加
     if ( (increase.size() == 1) && (decrease.size() == 0) ) {
         diffUID = increase[0];
         return 1; }
     // 物品除去
     if ( (increase.size() == 0) && (decrease.size() == 1) ) {
         diffUID = decrease[0];
         return -1; }
     // 複数物品の同時入出時（１個ずつ検出するようにする）
     if (increase.size() >= 1) {
         preUIDs.push_back(increase[0]);
         mUIDs[mActiveAntenna] = preUIDs;
         std::sort(mUIDs[mActiveAntenna].begin(), mUIDs[mActiveAntenna].end());
         mTagNum[mActiveAntenna] = (int)mUIDs[mActiveAntenna].size();
         diffUID = increase[0];
         return 1; }
     if (decrease.size() >= 1) {
         preUIDs.erase(remove(preUIDs.begin(), preUIDs.end(), decrease[0]),  preUIDs.end());
         mUIDs[mActiveAntenna] = preUIDs;
         std::sort(mUIDs[mActiveAntenna].begin(), mUIDs[mActiveAntenna].end());
         mTagNum[mActiveAntenna] = (int)mUIDs[mActiveAntenna].size();
         diffUID = decrease[0];
         return -1; }
     return 0; }
int CTR3::Inventory2 () private
Definition at line 543 of file ibs.cpp.
References AddChecksum(), fd, mActiveAntenna, mCommand, mTagNum, mTagUIDs, newtio, PORT_TR, TR3_ACK, TR3_TAG_MAX, TR3_TAG_SIZE, and TR3_UID_SIZE.
Referenced by GetTagDiff().
                      {
     //アンテナを変更しないと既読込のUIDは返さず，新規UIDのみ返す
     // unsigned long num;
     int i, j;
     static unsigned char buf[TR3_TAG_SIZE * TR3_TAG_MAX];
     mCommand[2] = 0x78; //コマンド
     mCommand[3] = 0x03; //データ長
     mCommand[4] = 0xF0; //コマンド詳細
     mCommand[5] = 0x00; //アンチコリジョン有
     mCommand[6] = 0x01; //出力指定->取得データ数＋UIDデータ
     //通信関連初期化
     if ( (fd = open(PORT_TR.c_str(), (O_RDWR | O_NOCTTY) )) < 0 ) {
         printf("FAILED:TR3->OpenComPort: PORT_TR \n");
         exit(-1); }
     tcgetattr(fd, &oldtio);         /* 現在のシリアルポートの設定を待避させる*/
     memset(&newtio, 0, sizeof(newtio));
     newtio.c_cflag = B38400 | CS8 | CLOCAL | CREAD;
     newtio.c_iflag = IGNPAR | ICRNL;
     newtio.c_oflag = 0;
     newtio.c_lflag = ICANON;
     tcflush(fd, TCIFLUSH);
     tcsetattr(fd, TCSANOW, &newtio);
     AddChecksum();
     write(fd, mCommand, sizeof(mCommand));
     read(fd, buf, 9);
     if (buf[2] != TR3_ACK) {
         std::cerr << "TR3: SendCommandError -> Inventory2" << std::endl;
         usleep(100000);
         read(fd, buf, TR3_TAG_SIZE * TR3_TAG_MAX);
         return -1; }
     int tag_num = (int)buf[5];  //読み込むタグの数
     //-------------
     //タグ情報の読込
     for (i = 0; i < tag_num; i++) {
         read(fd, buf, TR3_TAG_SIZE);
         for (j = 0; j < TR3_UID_SIZE; j++) {
             mTagUIDs[mActiveAntenna][i][TR3_UID_SIZE - 1 - j] = buf[j + 5]; } }
     mTagNum[mActiveAntenna] = tag_num;
     tcsetattr(fd, TCSANOW, &oldtio);  /* 退避させた設定に戻す */
     close(fd);
     return tag_num; }
void CTR3::PrintTagUIDs ()
Definition at line 533 of file ibs.cpp.
References mTagNum, mUIDs, and TR3_USED_ANT_NUM.
{
     int i, j;
     for (i = 0; i < TR3_USED_ANT_NUM; i++) {
         std::cout << "\n:::: ANTENNA " << i + 1 << " ::::" << std::endl;
         for (j = 0; j < mTagNum[i]; j++) {
             std::cout << std::setw(3) << j + 1 << "-> " << mUIDs[i][j] << std::endl; } } }
int CTR3::SetAntenna (unsigned char AN = TR3_ANT1)
Definition at line 410 of file ibs.cpp.
References AddChecksum(), fd, mActiveAntenna, mCommand, newtio, PORT_TR, and TR3_ACK.
Referenced by GetTagDiff(), and CIntelCab::UpdateObj().
{
     unsigned char buf[100];
     mCommand[2] = 0x4E; //コマンド
     mCommand[3] = 0x02; //データ長
     mCommand[4] = 0x9C; //コマンド詳細
     mCommand[5] = AN; //アンテナ指定
     memset(&buf, 0, sizeof(buf));
     //通信関連初期化
     if ( (fd = open(PORT_TR.c_str(), (O_RDWR | O_NOCTTY) )) < 0 ) {
         printf("FAILED:TR3->OpenComPort: PORT_TR \n"); }
     tcgetattr(fd, &oldtio);         /* 現在のシリアルポートの設定を待避させる*/
     memset(&newtio, 0, sizeof(newtio));
     newtio.c_cflag = B38400 | CS8 | CLOCAL | CREAD;
     newtio.c_iflag = IGNPAR | ICRNL;
     newtio.c_oflag = 0;
     newtio.c_lflag = ICANON;
     tcflush(fd, TCIFLUSH);
     tcsetattr(fd, TCSANOW, &newtio);
     AddChecksum();
     write(fd, mCommand, sizeof(mCommand));
     read(fd, buf, 9);
     if (buf[2] != TR3_ACK) {
         read(fd, buf, 100);
         std::cerr << "TR3: SendCommandError -> SetAntenna" << std::endl;
         return -1; }
     mActiveAntenna = (int)buf[5];
     tcsetattr(fd, TCSANOW, &oldtio);  /* 退避させた設定に戻す */
     close(fd);
     return (int)buf[5]; }
bool CTR3::Setup ()
Definition at line 370 of file ibs.cpp.
References fd, mActiveAntenna, mCommand, mTagNum, mTagUIDs, newtio, PORT_TR, TR3_ANT1, TR3_STX, TR3_TAG_MAX, TR3_UID_SIZE, and TR3_USED_ANT_NUM.
Referenced by main().
                  {
     //数値初期化関連
     memset(mTagUIDs, 0, sizeof(unsigned char)*TR3_USED_ANT_NUM * TR3_TAG_MAX * TR3_UID_SIZE);
     mActiveAntenna = TR3_ANT1;
     for (int i = 0; i < TR3_USED_ANT_NUM; i++)
         mTagNum[i] = 0;
     mCommand[0] = TR3_STX;  //
     mCommand[1] = 0x00;     //アドレス
     if ( (fd = open(PORT_TR.c_str(), (O_RDWR | O_NOCTTY) )) < 0 ) {
         printf("ERROR!!\n");
         exit(-1); }
     tcgetattr(fd, &oldtio);         /* 現在のシリアルポートの設定を待避させる*/
     memset(&newtio, 0, sizeof(newtio));
     newtio.c_cflag = B38400 | CS8 | CLOCAL | CREAD;
     newtio.c_iflag = IGNPAR | ICRNL;
     newtio.c_oflag = 0;
     newtio.c_lflag = ICANON;
     tcflush(fd, TCIFLUSH);
     tcsetattr(fd, TCSANOW, &newtio);
     tcsetattr(fd, TCSANOW, &oldtio);  /* 退避させた設定に戻す */
     close(fd);
     std::cout << "OPENED: TR3(port:" << PORT_TR.c_str() << ")" << std::endl;
     return true; }
Field Documentation
int CTR3::fd
Definition at line 147 of file ibs.cpp.
Referenced by AntennaPowerOFF(), AntennaPowerON(), Close(), Inventory2(), SetAntenna(), and Setup().
int CTR3::mActiveAntenna private
true active antenna returned by serial
Definition at line 128 of file ibs.cpp.
Referenced by GetTagDiff(), Inventory2(), SetAntenna(), and Setup().
unsigned char CTR3::mCommand[TR3_MAX_COMMAND_SIZE] private
Definition at line 126 of file ibs.cpp.
Referenced by AddChecksum(), AntennaPowerOFF(), AntennaPowerON(), Inventory2(), SetAntenna(), and Setup().
int CTR3::mTagNum[TR3_USED_ANT_NUM]
number of enxisting tags by the antenna
Definition at line 133 of file ibs.cpp.
Referenced by GetTagDiff(), Inventory2(), PrintTagUIDs(), and Setup().
unsigned char CTR3::mTagUIDs[TR3_USED_ANT_NUM][TR3_TAG_MAX][TR3_UID_SIZE]
same as mUIDs. should be replaced.
Definition at line 135 of file ibs.cpp.
Referenced by GetTagDiff(), Inventory2(), and Setup().
vec_str CTR3::mUIDs[TR3_USED_ANT_NUM]
UIDs of existing tags.
Definition at line 136 of file ibs.cpp.
Referenced by GetTagDiff(), and PrintTagUIDs().
struct termios oldtio CTR3::newtio private
Definition at line 124 of file ibs.cpp.
Referenced by AntennaPowerOFF(), AntennaPowerON(), Inventory2(), SetAntenna(), and Setup().
The documentation for this class was generated from the following file:
src/ibs.cpp