ibs: CLoadCell Class Reference
CLoadCell Class Reference
Public Member Functions
CLoadCell ()
~CLoadCell ()
bool Setup ()
void ResetWeight (int initial[]=NULL, int num=10)
void SetSensorPos (int sensor_num, float x[], float y[])
int GetWeight (int sensor_id)
int GetWeightDiff (float *x, float *y, int diffs[], int threshold=20)
Data Fields
int mSensorNum
int fd
Private Member Functions
bool Close ()
void OpenPort ()
void ClosePort ()
Private Attributes
struct termios oldtio newtio
int mPreSensorsWeight [LC_MAX_SENSOR_NUM]
float mSensorPosX [LC_MAX_SENSOR_NUM]
float mSensorPosY [LC_MAX_SENSOR_NUM]
Detailed Description
Definition at line 105 of file ibs.cpp.
Constructor & Destructor Documentation
CLoadCell::CLoadCell () inline
Definition at line 116 of file ibs.cpp.
 {};
CLoadCell::~CLoadCell () inline
Definition at line 117 of file ibs.cpp.
References Close().
                  {
         Close(); };
Member Function Documentation
bool CLoadCell::Close () private
Definition at line 226 of file ibs.cpp.
References fd.
Referenced by ~CLoadCell().
                       {
     close(fd);
     std::cout << "CLOSED: LoadCell" << std::endl;
     return true; }
void CLoadCell::ClosePort () private
Definition at line 250 of file ibs.cpp.
References D_COUT, fd, and PORT_LC0.
Referenced by GetWeight(), and Setup().
{
     tcsetattr(fd, TCSANOW, &oldtio);  /* 退避させた設定に戻す */
     D_COUT("closing port : " << PORT_LC0 << "   ");
     close(fd);
     D_COUT("\033[1K\r");
 }
int CLoadCell::GetWeight (int sensor_id)
Definition at line 266 of file ibs.cpp.
References ClosePort(), fd, and OpenPort().
Referenced by GetWeightDiff(), and ResetWeight().
{
     char signal, buf[20];
     memset(&buf, 0, sizeof(buf));
     // センサ番号からセンサのアドレスを求める
     if (0 <= sensor_id && sensor_id <= 9)
         signal = sensor_id + '0'; // 0->'0', 1->'1', ..., 9->'9'
     else
         signal = sensor_id - 10 + 'A'; // 10->'A', 11->'B', ... , 35->'Z'
     OpenPort();
     write(fd, &signal, 1);
     read(fd, buf, 15);
     ClosePort();
     int output_value = atoi(buf);
     // センサ出力を校正して返す
     return (int)(output_value * 5); //0.28は経験的な値
 }
int CLoadCell::GetWeightDiff (float * x, float * y, int diffs[], int threshold = 20)
Definition at line 304 of file ibs.cpp.
References GetWeight(), LC_GET_WEIGHT_CNT, LC_GET_WEIGHT_STABLE, LC_MAX_SENSOR_NUM, mPreSensorsWeight, mSensorNum, mSensorPosX, and mSensorPosY.
Referenced by CIntelCab::UpdateObj().
{
     static int i, j, cnt, weight;
     static int now, pre[LC_MAX_SENSOR_NUM], buf[LC_GET_WEIGHT_CNT][LC_MAX_SENSOR_NUM];//, latest[LC_MAX_SENSOR_NUM];
     //出力が安定するまで待つ
     for (i = 0; i < mSensorNum; i++) {
         pre[i] = GetWeight(i); }
     cnt = 0;    //繰り返し回数
     /*------------------------------------------*/
     do {
         //usleep(4000); //4ms程度は間隔を空ける
         usleep(20000);  //for demo
         weight = 0;
         for (i = 0; i < mSensorNum; i++) {
             now = GetWeight(i);
             weight += abs(now - pre[i]);
             pre[i] = now;
             buf[cnt][i] = now; }
         if (weight < LC_GET_WEIGHT_STABLE) {
             cnt++; }
         else {
             cnt = 0; } }
     while (cnt < LC_GET_WEIGHT_CNT);
     /*------------------------------------------*/
     //出力
     for (i = 0; i < mSensorNum; i++) {
         pre[i] = 0; }
     for (i = 0; i < LC_GET_WEIGHT_CNT; i++) {
         for (j = 0; j < mSensorNum; j++) {
             pre[j] += buf[i][j]; } }
     for (i = 0; i < mSensorNum; i++) {
         pre[i] /= LC_GET_WEIGHT_CNT;
         diffs[i] = pre[i] - mPreSensorsWeight[i]; }
     *x = *y = 0;
     weight = 0;
     for (i = 0; i < mSensorNum; i++) {
         *x += (float)(mSensorPosX[i] * abs(diffs[i]));
         *y += (float)(mSensorPosY[i] * abs(diffs[i]));
         weight += diffs[i]; }
     *x /= abs(weight);
     *y /= abs(weight);
     if (abs(weight) < threshold) {
         return 0; }
     else {
         for (i = 0; i < mSensorNum; i++) {
             mPreSensorsWeight[i] = pre[i]; }
         return weight; } }
void CLoadCell::OpenPort () private
Definition at line 232 of file ibs.cpp.
References D_COUT, fd, newtio, and PORT_LC0.
Referenced by GetWeight(), and Setup().
{
     //通信関連初期化
     D_COUT("opening port : " << PORT_LC0 << "   ");
     if ( (fd = open(PORT_LC0.c_str(), (O_RDWR | O_NOCTTY) )) < 0 ) {
         printf("FAILED: LoadCell->OpenComPort:PORT_LC0 \n");
         exit(-1); }
     D_COUT("\033[1K\r");
     tcgetattr(fd, &oldtio);         /* 現在のシリアルポートの設定を待避させる*/
     memset(&newtio, 0, sizeof(newtio));
     newtio.c_cflag = B115200 | CS8 | CLOCAL | CREAD;
     newtio.c_iflag = IGNPAR;
     newtio.c_oflag = 0;
     newtio.c_lflag = 0;
     newtio.c_cc[VTIME] = 0;
     newtio.c_cc[VMIN] = 15;            /* 15文字受け取るまでブロックする */
     tcflush(fd, TCIFLUSH);
     tcsetattr(fd, TCSANOW, &newtio);}
void CLoadCell::ResetWeight (int initial[] = NULL, int num = 10)
Definition at line 284 of file ibs.cpp.
References GetWeight(), mPreSensorsWeight, and mSensorNum.
Referenced by Setup().
{
     int i, j;
     if (initial != NULL) {
         for (i = 0; i < mSensorNum; i++)
             mPreSensorsWeight[i] = initial[i];
         return; }
     for (i = 0; i < mSensorNum; i++)
         mPreSensorsWeight[i] = 0;
     for (i = 0; i < num; i++)
         for (j = 0; j < mSensorNum; j++)
             mPreSensorsWeight[j] += GetWeight(j);
     for (i = 0; i < mSensorNum; i++)
         mPreSensorsWeight[i] /= num; }
void CLoadCell::SetSensorPos (int sensor_num, float x[], float y[])
Definition at line 258 of file ibs.cpp.
References mSensorNum, mSensorPosX, and mSensorPosY.
Referenced by CStage::SetSensorPos().
{
     mSensorNum = sensor_num;
     for (int i = 0; i < mSensorNum; i++) {
         mSensorPosX[i] = x[i];
         mSensorPosY[i] = y[i]; } }
bool CLoadCell::Setup ()
Definition at line 210 of file ibs.cpp.
References ClosePort(), LC_MAX_SENSOR_NUM, mPreSensorsWeight, mSensorNum, mSensorPosX, mSensorPosY, OpenPort(), PORT_LC0, and ResetWeight().
Referenced by CStage::Setup().
                       {
     //数値初期化関連
     for (int i = 0; i < LC_MAX_SENSOR_NUM; i++) {
         mPreSensorsWeight[i] = 0;
         mSensorPosX[i] = 0;
         mSensorPosY[i] = 0; }
     mSensorNum = LC_MAX_SENSOR_NUM;
     std::cout << "OPENING: LoadCell(port:" << PORT_LC0.c_str() << ")" << std::endl;
     OpenPort();
     std::cout << "OPENED: LoadCell(port:" << PORT_LC0.c_str() << ")" << std::endl;
     ClosePort();
     std::cout << "CLOSED: LoadCell(port:" << PORT_LC0.c_str() << ")" << std::endl;
     ResetWeight();
     return true; }
Field Documentation
int CLoadCell::fd
Definition at line 126 of file ibs.cpp.
Referenced by Close(), ClosePort(), GetWeight(), and OpenPort().
int CLoadCell::mPreSensorsWeight[LC_MAX_SENSOR_NUM] private
Definition at line 111 of file ibs.cpp.
Referenced by GetWeightDiff(), ResetWeight(), and Setup().
int CLoadCell::mSensorNum
Definition at line 121 of file ibs.cpp.
Referenced by GetWeightDiff(), ResetWeight(), SetSensorPos(), and Setup().
float CLoadCell::mSensorPosX[LC_MAX_SENSOR_NUM] private
Definition at line 112 of file ibs.cpp.
Referenced by GetWeightDiff(), SetSensorPos(), and Setup().
float CLoadCell::mSensorPosY[LC_MAX_SENSOR_NUM] private
Definition at line 113 of file ibs.cpp.
Referenced by GetWeightDiff(), SetSensorPos(), and Setup().
struct termios oldtio CLoadCell::newtio private
Definition at line 107 of file ibs.cpp.
Referenced by OpenPort().
The documentation for this class was generated from the following file:
src/ibs.cpp