uint32 id
sensor_msgs/PointCloud2 cloud
sensor_msgs/PointCloud2 model
geometry_msgs/Pose furniture
geometry_msgs/Pose2D robot
geometry_msgs/Pose sensor
---
sensor_msgs/PointCloud2 cloud
geometry_msgs/PoseArray objects
